comps/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'comps'

urlpatterns = [
    path('administrace/zavody', views.CompsView, name='compsView'),
    url('NewComp', views.NewComp, name='NewComp'),
    path('deleteComp/<int:ids>', views.deleteComp, name='deleteComp'),
    path('administrace/kategorie/<int:ids>', views.categoryView, name='categoryView'),
    path('newCategory/<int:ids>', views.NewCategory, name='newCategory'),
    path('deleteCategory/<int:compId>/<int:categoryId>', views.deleteCategory, name='deleteCategory'),
    path('administrace/moji-zavodnici/registrace/<int:racerId>', views.registrationView, name='registration'),
    path('changeRegistration/<int:categoryId>/<int:racerId>', views.changeRegistration, name='changeRegistration'),
    path('seznam-prihlasenych', views.listOfCompWithRegistrateList, name='listOfComps'),
    path('seznam-prihlasenych/<int:compId>', views.listOfRegistrate, name='listOfRegistrate'),
    path('zadani-vysledku/<int:compId>/<int:categoryId>', views.changeResults, name='changeResult_2'),
    path('zadani-vysledku/<int:compId>', views.changeResults, name='changeResult_1'),
    path('zadani-vysledku', views.changeResults, name='changeResult_0'),
    path('vysledky/<int:compId>/<int:categoryId>', views.getResults, name='getResults_2'),
    path('vysledky/<int:compId>', views.getResults, name='getResults_1'),
    path('vysledky', views.getResults, name='getResults_0'),
    path('startovni-listina/<int:categoryId>', views.getStartsList, name='startersPdf'),
    path('administrace-uzivatelu', views.usersView, name='users'),
    path('deleteUser/<email>', views.deleteUser, name='deleteUser'),

    path('vysledky-pdf/<int:categoryId>', views.getResultPdf, name='resultPdf'),
    path('saveChangeResults/<int:compId>/<int:categoryId>', views.saveChangeResults, name='saveChangeResults'),

]

polls/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'polls'


urlpatterns = [
    path('', views.HomepageDefaultView),
    url('myLogout', views.myLogout, name='myLogout'),
    path('prihlaseni', views.LoginView, name='login'),
    path('administrace', views.AdministrationView, name='administration'),
    path('administrace/moji-zavodnici', views.CompetitorsView),
    url('newRacer', views.newRacer, name='newRacer'),
    path('deleteRacer/<int:ids>', views.deleteRacer, name='deleteRacer'),
    path('regitrace', views.RegistrationVIew, name='registration'),
]

semestralka/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from polls.views import *

urlpatterns = [
    path('', include('polls.urls')),
    path('', include('comps.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'public/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'public/style/css/style.css' %}">
  <title>Titlepublic</title>
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <a class="nav-link text-white" href="/">domů</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link text-white" href="{% url 'comps:listOfComps' %}">seznam přihlášených</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'polls:administration' %}">administrace</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'comps:getResults_0' %}">výsledky</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if not user.is_authenticated  %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'polls:login' %}"><i class="fa fa-sign-in"></i> přihlášení</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'polls:registration' %}"><i class="fa fa-sign-in"></i> registrace</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link text-white" href="#"><i class="fa fa-user"></i> {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'polls:myLogout' %}"><i class="fa fa-sign-in"></i> odhlasit</a>
          </li>
        {% endif %}
      </ul>
    </div>
    </nav>

 {% if messages %}
      {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }} alert"{% endif %} style="position: absolute; width: 100%;">{{ message }}</div>
      {% endfor %}
{% endif %}

        {% block content %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</body>
</html>

<script>
$(document).ready(function() {
  if ($('div').hasClass('fmgShort')) {
    setTimeout(function(){
        $(".fmgShort").hide('slow');}, 3000);
  }
});

</script>