comps/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'comps'

urlpatterns = [
    path('administrace/zavody', views.CompsView, name='compsView'),
    url('NewComp', views.NewComp, name='NewComp'),
    path('deleteComp/<int:ids>', views.deleteComp, name='deleteComp'),
    path('administrace/kategorie/<int:ids>', views.categoryView, name='categoryView'),
    path('newCategory/<int:ids>', views.NewCategory, name='newCategory'),
    path('deleteCategory/<int:compId>/<int:categoryId>', views.deleteCategory, name='deleteCategory'),
    path('administrace/moji-zavodnici/registrace/<int:racerId>', views.registrationView, name='registration'),
    path('changeRegistration/<int:categoryId>/<int:racerId>', views.changeRegistration, name='changeRegistration'),
    path('seznam-prihlasenych', views.listOfCompWithRegistrateList, name='listOfComps'),
    path('seznam-prihlasenych/<int:compId>', views.listOfRegistrate, name='listOfRegistrate'),
    path('zadani-vysledku/<int:compId>/<int:categoryId>', views.changeResults, name='changeResult_2'),
    path('zadani-vysledku/<int:compId>', views.changeResults, name='changeResult_1'),
    path('zadani-vysledku', views.changeResults, name='changeResult_0'),
    path('vysledky/<int:compId>/<int:categoryId>', views.getResults, name='getResults_2'),
    path('vysledky/<int:compId>', views.getResults, name='getResults_1'),
    path('vysledky', views.getResults, name='getResults_0'),
    path('startovni-listina/<int:categoryId>', views.getStartsList, name='startersPdf'),
    path('administrace-uzivatelu', views.usersView, name='users'),
    path('deleteUser/<email>', views.deleteUser, name='deleteUser'),

    path('vysledky-pdf/<int:categoryId>', views.getResultPdf, name='resultPdf'),
    path('saveChangeResults/<int:compId>/<int:categoryId>', views.saveChangeResults, name='saveChangeResults'),

]

polls/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'polls'


urlpatterns = [
    path('', views.HomepageDefaultView),
    url('myLogout', views.myLogout, name='myLogout'),
    path('prihlaseni', views.LoginView, name='login'),
    path('administrace', views.AdministrationView, name='administration'),
    path('administrace/moji-zavodnici', views.CompetitorsView),
    url('newRacer', views.newRacer, name='newRacer'),
    path('deleteRacer/<int:ids>', views.deleteRacer, name='deleteRacer'),
    path('regitrace', views.RegistrationVIew, name='registration'),
]

semestralka/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from polls.views import *

urlpatterns = [
    path('', include('polls.urls')),
    path('', include('comps.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

comps/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View

from .models import *
from polls import models
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas


# ----------------------Comps--------------------------------
def NewComp(request):
    if request.method == "POST":
        type = 'alert-success'
        try:
            comp = Comps()
            if request.POST['edit'] is '0':
                comp.newComp(request)
                message = 'Závod byl úspěšně přidán!'
            else:
                comp.editComp(request)
                message = 'Závod byl úspěšně upraven!'
        except:
            message = 'Operace se nepovedla!'
            type = 'alert-danger'

        messages.add_message(request, messages.INFO, message, 'fmgShort ' + type)
        return HttpResponseRedirect('/administrace/zavody')


def CompsView(request):
    if not request.user.is_superuser:
        messages.add_message(request, messages.INFO, 'Neoprávnění přístup', 'fmgShort alert-danger')
        return render(request, 'public/homepage.html')
    return render(request, 'private/comps.html', dict(comps=Comps.objects.all(),
                                                      comp_type_dict=Comps().getDictCompType(),
                                                      state_dict=Comps().getDictState()))


def deleteComp(request, ids):
    try:
        Comps.objects.get(id=ids).delete()
        messages.add_message(request, messages.INFO, 'Závod byl smazán!', 'fmgShort alert-success')
    except:
        messages.add_message(request, messages.ERROR, 'Operace se nepovedla!', 'fmgShort alert-danger')

    return HttpResponseRedirect('/administrace/zavody')


# --------------------------category------------------------------

def categoryView(request, ids):
    if not request.user.is_superuser:
        messages.add_message(request, messages.INFO, 'Neoprávnění přístup', 'fmgShort alert-danger')
        return render(request, 'public/homepage.html')
    return render(request, 'private/category.html',
                  dict(comp=Comps.objects.get(id=ids), categoryToComp=Category.objects.all().filter(comp_id=ids))
                  )


def NewCategory(request, ids):
    if request.method == "POST":
        type = 'alert-success'
        category = Category()
        try:
            if request.POST['edit'] is '0':
                category.newCategory(request)
                message = 'Kategorie byla úspěšně přidána!'
            else:
                category.editCategory(request)
                message = 'Kategorie byla úspěšně upravena!'
        except:
            message = 'Operace se nepovedla!'
            type = 'alert-danger'

        messages.add_message(request, messages.INFO, message, 'fmgShort ' + type)
    return HttpResponseRedirect('/administrace/kategorie/' + str(ids))


def deleteCategory(request, compId, categoryId):
    try:
        Category.objects.get(id=categoryId).delete()
        messages.add_message(request, messages.INFO, 'Kategorie byla smazána!', 'fmgShort alert-success')
    except:
        messages.add_message(request, messages.ERROR, 'Operace se nepovedla!', 'fmgShort alert-danger')

    return HttpResponseRedirect('/administrace/kategorie/' + str(compId))


# --------------------------registration------------------------------

def registrationView(request, racerId):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.INFO, 'Neoprávnění přístup', 'fmgShort alert-danger')
        return render(request, 'public/homepage.html')
    return render(request, 'private/registration.html',
                  dict(comps=Comps.objects.all().filter(state='precomp'), comp_type_dict=Comps().getDictCompType(),
                       registration=Registration, racer=models.Racer.objects.get(id=racerId))
                  )
def changeRegistration(request, categoryId, racerId):
    message = 'Operace se nepovedla!'
    type = 'alert-success'
    category = Category.objects.get(id=categoryId)
    racer = models.Racer.objects.get(id=racerId)
    registration = Registration.objects.all().filter(category=category, racer=racer)
    try:
        if not registration:
            Registration.objects.create(category=category, racer=racer)
            message = 'Závodník byl úspěšně přihlášen.'
        else:
            registration.delete()
            message = 'Závodník byl úspěšně odhlášen.'
    except:
        type = 'alert-danger'

    messages.add_message(request, messages.INFO, message, 'fmgShort ' + type)
    return HttpResponseRedirect('/administrace/moji-zavodnici/registrace/' + str(racerId))

# --------------------------Users------------------------------

def usersView(request):
    if not User.is_superuser:
        messages.add_message(request, messages.INFO, 'Neoprávnění přístup', 'fmgShort alert-danger')
        return render(request, 'public/homepage.html')
    return render(request, 'private/users.html', dict(users=User.objects.filter(is_superuser=0)))

def deleteUser(request, email):
    try:
        user = User.objects.filter(email=email)
        user.delete()
    except:
        messages.add_message(request, messages.INFO, 'smazani uzivatele se nepovedlo', 'fmgShort ', 'danger')

    messages.add_message(request, messages.INFO, 'uživatel byl úspěšně smazán', 'fmgShort ', 'success')
    return HttpResponseRedirect('/administrace-uzivatelu')

# --------------------------listOfCompWithpublicRegistarteList------------------------------

def listOfCompWithRegistrateList(request):
    categories = Category.objects.all().filter()
    comps = Comps.objects.all().filter(state__in=('precomp', 'running'))
    return render(request, 'public/listOfCompsWithRegistrate.html', dict(comps=comps))


def listOfRegistrate(request, compId):
    return render(request, 'public/listOfRegistrate.html', dict(categories=Category.objects.all().filter(comp_id=compId)))


# --------------------------listOfCompWithpublicRegistarteList------------------------------
def getStartsList(request, categoryId):
    pdf = getStartersPdf(categoryId)
    return HttpResponse(pdf, content_type='application/pdf')

def getResultPdf(request, categoryId):
    pdf = getResultToPdf(categoryId)
    return HttpResponse(pdf, content_type='application/pdf')



def changeResults(request, compId=None, categoryId=None):
    dictToRender = dict(compId=compId, categoryId=categoryId)
    if compId and categoryId:
        dictToRender['category'] = Category.objects.get(id=categoryId)
        dictToRender['comp'] = Comps.objects.get(id=compId)
        dictToRender['registrations'] = Registration.objects.filter(category_id=categoryId, )
    elif compId:
        dictToRender['categories'] = Category.objects.filter(comp_id=compId)
        dictToRender['comp'] = Comps.objects.get(id=compId)
    else:
        dictToRender['comps'] = Comps.objects.filter(state='running')
    return render(request, 'private/changeResults.html', dictToRender)


def saveChangeResults(request, compId, categoryId):
    registration = Registration()
    registration.changeResult(request)
    return HttpResponseRedirect('/zadani-vysledku/' + str(compId) + '/' + str(categoryId))

def getResults(request, compId=None, categoryId=None):
    dictToRender = dict(compId=compId, categoryId=categoryId)
    if compId and categoryId:
        registration = Registration()
        comp = Comps.objects.get(id=compId)

        dictToRender['category'] = Category.objects.get(id=categoryId)
        dictToRender['comp'] = comp
        dictToRender['registrations'] = Registration.objects.filter(category_id=categoryId, )
        dictToRender['place'] = registration.getResults(categoryId)



    elif compId:
        dictToRender['categories'] = Category.objects.filter(comp_id=compId)
        dictToRender['comp'] = Comps.objects.get(id=compId)
    else:
        comps = Comps.objects.filter(state='running')
        dictToRender['comps'] = Comps.objects.filter(state='running')
        if comps.count() == 1:
            for comp in comps:
                dictToRender['compId'] = comp.id
                dictToRender['categories'] = Category.objects.filter(comp_id=comp.id)
                dictToRender['comp'] = Comps.objects.get(id=comp.id)

    return render(request, 'public/results.html', dictToRender)

templates/private/administration.html
{% extends 'base.html' %}
{% block content %}
  <div class="container text-center container-padding-top">
    <a href="administrace/moji-zavodnici" class="btn btn-primary">moji závodníci</a>
    {% if user.is_superuser %}
      <a href="administrace/zavody" class="btn btn-primary"> závody</a>
      <a href="{% url 'comps:changeResult_0' %}" class="btn btn-primary">zadat výsledky</a>
      <a href="{% url 'comps:users' %}" class="btn btn-primary">správa uživatelů</a>
    {% endif %}
   </div>
{% endblock %}

templates/private/category.html
{% extends 'base.html' %}
{% load comps_filters %}
{% block content %}
  <div class="container text-center container-padding-top">

    <form method="post" action="/newCategory/{{ comp.id }}">
      {% csrf_token %}
      <div class="form-row">
        <label for="inputEmail3" class="col-md-2 col-form-label"><h5>kategorie:</h5></label>
        <div class="col-md-3">
          <input class="form-control" type="text" name="name" id="name" placeholder="Jméno" required/>
        </div>
        <div class="col-md-2">
          <select id="sex" class="form-control" name="sex" required>
             <option value="" disabled selected>pohlaví</option>
            <option value="male">chlapci / muži</option>
            <option value="female">dívky / ženy </option>
          </select>
        </div>
        <div class="col-md-2">
          <input class="form-control" type="number" name="year_from" id="year_from" placeholder="nejmladší (rok)" required>
        </div>
        <div class="col-md-2">
          <input class="form-control" type="number" name="year_to" id="year_to" placeholder="nejstarší(rok)" required>
        </div>
        <div class="col-md-1">
          <input class="form-control" type="number" name="edit" value="0" id="edit" hidden>
          <input class="form-control" type="text" name="comp_id" id="comp_id" value="{{ comp.id }}" hidden>
          <input type="submit" value="Uložit" class="btn btn-primary btn-block">
        </div>
      </div>
    </form>

    <br><br>
    <table class="table table-striped text-left table-responsive-md">
      <thead>
      <tr>
        <th>#</th>
        <th>kategorie</th>
        <th>pohlaví</th>
        <th>ročník</th>
        <th style="width: 200px">akce</th>
      </tr>
      </thead>
      <tbody>
      {% for category in categoryToComp %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ category.name }}</td>
          <td>{{ category.sex }}</td>
          <td>{{ category.getYear }}</td>
          <td>
            <div class="text-nowrap">
              <a class="btn btn-primary" href="{% url 'comps:deleteCategory' compId=comp.id categoryId=category.id %}">smazat</a>
              <a class="btn btn-primary" href="#"
                 onclick="editCategory('{{ category.id }}', '{{ category.name }}', '{{ category.year_from }}', '{{ category.year_to }}', '{{ category.sex }}')">upravit</a>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  </div>

  <script>
      function editCategory(ids, name, year_from, year_to, sex) {
          $('#edit').val(ids);
          $('#name').val(name);
          $('#sex').val(sex);
          $('#year_from').val(year_from);
          $('#year_to').val(year_to);
      }
  </script>
{% endblock %}

templates/private/changeResults.html
{% extends 'base.html' %}
{% load comps_filters %}
{% block content %}
  <div class="container text-center container-padding-top">
    {% if compId and categoryId %}
      {% if comp.type == '0' %}
        <form method="post" action="{% url 'comps:saveChangeResults' compId=compId categoryId=categoryId %}">
          {% csrf_token %}
            <table class="table table-striped text-left">
              <thead>
              <tr>
                <th>#</th>
                <th>jméno</th>
                <th>oddil</th>
                <th>rok narození</th>
                <th>cesta 1</th>
                <th>cesta 2</th>
              </tr>
              </thead>
              <tbody>
              {% for registration in registrations %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ registration.racer }}</td>
                  <td>{{ registration.racer.club }}</td>
                  <td>{{ registration.racer.born }}</td>
                  <td><input name="lead_route_1__{{ registration.id  }}" type="number" value="{{ registration.lead_route_1 }}" style="width: 100px"></td>
                  <td><input name="lead_route_2__{{ registration.id  }}" type="number" value="{{ registration.lead_route_2 }}" style="width: 100px"/></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div>
              <a href="{% url 'comps:resultPdf' categoryId %}" class="btn btn-primary">Tisk do pdf</a>
              <input type="submit" class="btn btn-primary pull-right" value="Uložit"/>
            </div>
        </form>
      {% elif  comp.type == '2' %}
        <form method="post" action="{% url 'comps:saveChangeResults' compId=compId categoryId=categoryId %}">
          {% csrf_token %}
            <table class="table table-striped text-left">
              <thead>
              <tr>
                <th>#</th>
                <th>jméno</th>
                <th>oddil</th>
                <th>rok narození</th>
                <th>pokus 1</th>
                <th>pokus 2</th>
                <th>pokus 3</th>
                <th>pokus 4</th>
              </tr>
              </thead>
              <tbody>
              {% for registration in registrations %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ registration.racer }}</td>
                  <td>{{ registration.racer.club }}</td>
                  <td>{{ registration.racer.born }}</td>
                  <td><input name="speed_1__{{ registration.id  }}" type="number" step="any" value="{{ registration.speed_1 }}" style="width: 100px"></td>
                  <td><input name="speed_2__{{ registration.id  }}" type="number" step="any" value="{{ registration.speed_2 }}" style="width: 100px"/></td>
                  <td><input name="speed_3__{{ registration.id  }}" type="number" step="any" value="{{ registration.speed_3 }}" style="width: 100px"/></td>
                  <td><input name="speed_4__{{ registration.id  }}" type="number" step="any" value="{{ registration.speed_4 }}" style="width: 100px"/></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div>
              <a href="{% url 'comps:resultPdf' categoryId %}" class="btn btn-primary">Tisk do pdf</a>
              <input type="submit" class="btn btn-primary pull-right" value="Uložit"/>
            </div>
        </form>
      {% elif comp.type == '1' %}
 <form method="post" action="{% url 'comps:saveChangeResults' compId=compId categoryId=categoryId %}">
          {% csrf_token %}
            <table class="table table-striped text-left">
              <thead>
              <tr>
                <th>#</th>
                <th>jméno</th>
                <th>oddil</th>
                <th>rok narození</th>
                <th>B1Z</th>
                <th>B1T</th>
                <th>B2Z</th>
                <th>B2T</th>
                <th>B3Z</th>
                <th>B3T</th>
                <th>B4Z</th>
                <th>B4T</th>
                <th>B5Z</th>
                <th>B5T</th>
                <th>B6Z</th>
                <th>B6T</th>
              </tr>
              </thead>
              <tbody>
              {% for registration in registrations %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ registration.racer }}</td>
                  <td>{{ registration.racer.club }}</td>
                  <td>{{ registration.racer.born }}</td>
                  <td><input name="boulder_1_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_1_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_1_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_1_top }}" style="width: 50px"></td>
                  <td><input name="boulder_2_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_2_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_2_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_2_top }}" style="width: 50px"></td>
                  <td><input name="boulder_3_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_3_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_3_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_3_top }}" style="width: 50px"></td>
                  <td><input name="boulder_4_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_4_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_4_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_4_top }}" style="width: 50px"></td>
                  <td><input name="boulder_5_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_5_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_5_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_5_top }}" style="width: 50px"></td>
                  <td><input name="boulder_6_zone__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_6_zone }}" style="width: 50px"></td>
                  <td><input name="boulder_6_top__{{ registration.id  }}" type="number" step="any" value="{{ registration.boulder_6_top }}" style="width: 50px"></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <div>
              <a href="{% url 'comps:resultPdf' categoryId %}" class="btn btn-primary">Tisk do pdf</a>
              <input type="submit" class="btn btn-primary pull-right" value="Uložit"/>
            </div>
        </form>
      {% endif %}

    {% elif compId %}

      {% for cat in categories %}
        <a href="{% url 'comps:changeResult_2' compId=compId categoryId=cat.id %}"
           class="btn btn-primary">{{ cat.name }}</a>
      {% endfor %}

    {% else %}

      {% for comp in comps %}
        <a href="{% url 'comps:changeResult_1' compId=comp.id %}" class="btn btn-primary">{{ comp.name }}</a>
      {% endfor %}

    {% endif %}
  </div>
{% endblock %}

templates/private/comps.html
{% extends 'base.html' %}
{% load comps_filters %}
{% block content %}
  <div class="container text-center container-padding-top">

    <form method="post" action="/NewComp/">
      {% csrf_token %}
      <input class="form-control" type="number" name="edit" value="0" id="edit" hidden required>
      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control" id="name" name="name" placeholder="Jméno závodu" required>
        </div>
        <div class="form-group col-md-4">
          <input placeholder="Začátek závodu" class="form-control" name="start_date" type="text" onfocus="(this.type='date')" onblur="(this.type='text')" id="start_date" required />
        </div>
        <div class="form-group col-md-4">
          <input placeholder="Konec závodu" class="form-control" name="end_date" type="text" onfocus="(this.type='date')" onblur="(this.type='text')" id="end_date" required />
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4">
          <select class="form-control" name="type" id="type" required>
            <option value="" disabled selected >typ závodu</option>
            <option value="0">obtížnost</option>
            <option value="1">boulder</option>
            <option value="2">rychlost</option>
          </select>
        </div>
        <div class="form-group col-md-4">
          <input type="number" class="form-control" name="min_age" id="min_age" placeholder="spodní rok narozeni" required>
        </div>
        <div class="form-group col-md-4">
          <input type="number" class="form-control" name="max_age" id="max_age" placeholder="vrchní rok narozeni" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4">
          <select id="state" class="form-control" name="state" required>
             <option value="" disabled selected>stav závodu</option>
            <option value="prepare">příprava</option>
            <option value="precomp">registrace</option>
            <option value="running">probíhá</option>
            <option value="end">ukončen</option>
          </select>
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control" id="city" name="city" placeholder="Město" required>
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control" id="address" name="address" placeholder="Adresa" required>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-4"></div>
        <button type="submit" class="btn btn-primary btn-block col-md-4">Uložit</button>
      </div>


    </form>

    <br><br>
    <table class="table table-striped text-left table-responsive-md">
      <thead>
      <tr>
        <th>#</th>
        <th>Jméno</th>
        <th>Dataum konání</th>
        <th>typ</th>
        <th>věkový rozptyl</th>
        <th>stav</th>
        <th style="width: 200px">akce</th>
      </tr>
      </thead>
      <tbody>
      {% for comp in comps %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ comp.name }}</td>
          <td>
            {% if comp.start_date == comp.end_date %}
              {{ comp.start_date|date:"j. n. Y" }}
            {% else %}
              {{ comp.start_date|date:"j. n. Y" }} - {{ comp.end_date|date:"j. n. Y" }}
            {% endif %}
          </td>
          <td>{{ comp_type_dict|get_item:comp.type }}</td>
          <td>{{ comp.min_age }} až {{ comp.max_age }}</td>
          <td>{{ state_dict|get_item_string_key:comp.state }}</td>

          <td>
            <div class="text-nowrap">
              <a class="btn btn-primary" href="{% url 'comps:deleteComp' ids=comp.id %}">smazat</a>
              <a class="btn btn-primary" href="#" onclick="editComp( '{{ comp.id}}', '{{ comp.name}}','{{ comp.type }}' , '{{ comp.start_date|date:"Y-m-d" }}', '{{ comp.end_date|date:"Y-m-d"}}', '{{ comp.min_age}}', '{{ comp.max_age}}', '{{ comp.city}}', '{{ comp.address}}', '{{ comp.state }}' )">upravit</a>
              <a class="btn btn-primary" href="{% url 'comps:categoryView' ids=comp.id %}">kategorie</a>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  </div>

    <script>
    function editComp(ids, name, type, start_date, end_date, min_age, max_age, city, address, state) {
        $('#name').val(name);
        $('#type').val(type);
        $('#start_date').val(start_date);
        $('#end_date').val(end_date);
        $('#min_age').val(min_age);
        $('#max_age').val(max_age);
        $('#city').val(city);
        $('#address').val(address);
        $('#edit').val(ids);
        $('#state').val(state);
    }
  </script>
{% endblock %}

templates/private/racers.html
{% extends 'base.html' %}
{% block content %}
  <div class="container text-center container-padding-top">

    <form method="post" action="/newRacer/ {{ ids }}" >
      {% csrf_token %}
        <div class="form-row">
          <label for="inputEmail3" class="col-md-2 col-form-label"><h5>Závodník:</h5></label>
          <div class="col-md-2">
            <input class="form-control" type="text" name="first_name" id="first_name" placeholder="Jméno"/>
          </div>
          <div class="col-md-2">
            <input class="form-control" type="text" name="last_name" id="last_name" placeholder="Přijmení">
          </div>
          <div class="col-md-2">
            <input class="form-control" type="text" name="club" id="club" placeholder="Oddíl">
          </div>
          <div class="col-md-2">
            <select id="sex" class="form-control" name="sex" required>
               <option value="" disabled selected>pohlaví</option>
              <option value="male">chlapci / muži</option>
              <option value="female">dívky / ženy </option>
            </select>
          </div>
          <div class="col-md-2">
            <input class="form-control" type="number" name="born"  id ="born" placeholder="rok narození">
          </div>
          <div class="col-md-2">
            <input class="form-control" type="number" name="edit" value="0" id="edit" hidden>
            <input type="submit" value="Uložit" class="btn btn-primary btn-block">
          </div>
        </div>
    </form>

    <br><br>
    <table class="table table-striped text-left" style="background: white;">
      <thead>
        <tr>
          <th>#</th>
          <th>jméno</th>
          <th>oddil</th>
          <th>pohlaví</th>
          <th>rok narození</th>
          <th style="width: 200px">akce</th>
        </tr>
      </thead>
      <tbody>
      {% for racer in racers %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ racer }}</td>
          <td>{{ racer.club }}</td>
          <td>{{ racer.sex }}</td>
          <td>{{ racer.born }}</td>
          <td>
            <div class="text-nowrap">
              <a class="btn btn-primary" href="{% url 'polls:deleteRacer' ids=racer.id %}">smazat</a>
              <a class="btn btn-primary" href="#" onclick="editRacer('{{ racer.id }}' , '{{ racer.first_name}}', '{{ racer.last_name}}', '{{  racer.born }}', '{{ racer.club }}', '{{ racer.sex }}')">upravit</a>
              <a href="{% url 'comps:registration' racerId=racer.id %}" class="btn btn-primary">registrace</a>
            </div>
          </td>
        </tr>
     {% endfor %}
      </tbody>
    </table>
   </div>

  <script>
    function editRacer(ids, first_name, last_name, born, club, sex) {
        $('#first_name').val(first_name);
        $('#last_name').val(last_name);
        $('#sex').val(sex);
        $('#club').val(club);
        $('#born').val(born);
        $('#edit').val(ids);
    }
  </script>
{% endblock %}

templates/private/users.html
{% extends 'base.html' %}
{% load comps_filters %}
{% block content %}
  <div class="container text-center container-padding-top">
    <table class="table table-striped text-left table-responsive-md">
      <thead>
      <tr>
         <th>#</th>
         <th>uživatel</th>
         <th>akce</th>
      </tr>
      </thead>
      <tbody>
          {% for user in users %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ user }}</td>
              <td><a class="btn btn-primary" href="{% url 'comps:deleteUser' user %}">smazat</a></td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
  </div>
{% endblock %}